
json.extract! user,
              :id,
              :username,
              :photo_url,
              :zip_code,
              :role,
              :about,
              :looking_for,
              :mentor,
              :hiring,
              :friendship,
              :collaboration,
              :location,
              :question_responses,
              :questions,
              :question_options
